# CPack properties
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_BINARY_DIR}/COPYING.txt")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_BINARY_DIR}/README.txt")
set(CPACK_RESOURCE_FILE_WELCOME "${CMAKE_CURRENT_BINARY_DIR}/WELCOME.txt")

set(CPACK_ARCHIVE_COMPONENT_INSTALL ON)
set(CPACK_COMPONENTS_GROUPING ONE_PER_GROUP)

# coponents
set(CPACK_COMPONENTS_ALL UpstreamADevel)

# names & descriptions
set(CPACK_COMPONENT_UPSTREAMADEVEL_DISPLAY_NAME "Upstream A Development")
set(CPACK_COMPONENT_UPSTREAMADEVEL_DESCRIPTION "CMake support for Upstream A package.")

# requireds

# dependencies

# groups
# Runtime

# Development
set(CPACK_COMPONENT_UPSTREAMADEVEL_GROUP "Development")

