# CPack properties

# coponents
set(CPACK_COMPONENTS_ALL ${CPACK_COMPONENTS_ALL} Core CoreDevel PARENT_SCOPE)

# names & descriptions
set(CPACK_COMPONENT_CORE_DISPLAY_NAME "Core" PARENT_SCOPE)
file(READ ${CMAKE_CURRENT_SOURCE_DIR}/doc/DESCRIPTION CoreDescription)
set(CPACK_COMPONENT_CORE_DESCRIPTION ${CoreDescription} PARENT_SCOPE)

# requireds
set(CPACK_COMPONENT_CORE_REQUIRED ON PARENT_SCOPE)

# dependencies
set(CPACK_COMPONENT_COREDEVEL_DEPENDS BaseDevel PARENT_SCOPE)

# groups
# Runtime
set(CPACK_COMPONENT_CORE_GROUP "Runtime" PARENT_SCOPE)

# Development
set(CPACK_COMPONENT_COREDEVEL_GROUP "Development" PARENT_SCOPE)

