# CPack properties for libA

# components
set(CPACK_COMPONENTS_ALL ${CPACK_COMPONENTS_ALL} Lib LibDevel PARENT_SCOPE)

# name & description
set(CPACK_COMPONENT_LIB_DISPLAY_NAME "Lib" PARENT_SCOPE)
set(CPACK_COMPONENT_LIBDEVEL_DISPLAY_NAME "Lib Development" PARENT_SCOPE)

# required
set(CPACK_COMPONENT_LIB_REQUIRED ON PARENT_SCOPE)

# dependencies
set(CPACK_COMPONENT_LIBDEVEL_DEPENDS UpstreamADevel Lib PARENT_SCOPE)

# groups
# Runtime
set(CPACK_COMPONENT_LIB_GROUP "Runtime" PARENT_SCOPE)

# Development
set(CPACK_COMPONENT_LIBDEVEL_GROUP "Development" PARENT_SCOPE)

