# CPack properties
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_BINARY_DIR}/COPYING.txt")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_BINARY_DIR}/README.txt")
set(CPACK_RESOURCE_FILE_WELCOME "${CMAKE_CURRENT_BINARY_DIR}/WELCOME.txt")

set(CPACK_ARCHIVE_COMPONENT_INSTALL ON)
set(CPACK_COMPONENTS_GROUPING ONE_PER_GROUP)

# coponents
set(CPACK_COMPONENTS_ALL BaseDevel)

# names & descriptions
set(CPACK_COMPONENT_BASEDEVEL_DISPLAY_NAME "Base Development")
set(CPACK_COMPONENT_BASEDEVEL_DESCRIPTION "CMake support for Base package.")

# requireds

# dependencies

# groups
# Runtime

# Development
set(CPACK_COMPONENT_BASEDEVEL_GROUP "Development")

