# CPack properties for my app

# components
set(CPACK_COMPONENTS_ALL ${CPACK_COMPONENTS_ALL} MySApp MySAppDevel PARENT_SCOPE)

# name & description
set(CPACK_COMPONENT_MYSAPP_DISPLAY_NAME "App 1" PARENT_SCOPE)
set(CPACK_COMPONENT_MYSAPPDEVEL_DISPLAY_NAME "App 1 Development" PARENT_SCOPE)

# required
set(CPACK_COMPONENT_MYSAPP_REQUIRED ON PARENT_SCOPE)

# dependencies
set(CPACK_COMPONENT_MYSAPPDEVEL_DEPENDS MySAppDevel MySApp PARENT_SCOPE)

# groups
# Runtime
set(CPACK_COMPONENT_MYSAPP_GROUP "Runtime" PARENT_SCOPE)

# Development
set(CPACK_COMPONENT_MYSAPPDEVEL_GROUP "Development" PARENT_SCOPE)

