# CPack properties
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_BINARY_DIR}/COPYING.txt")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_BINARY_DIR}/README.txt")
set(CPACK_RESOURCE_FILE_WELCOME "${CMAKE_CURRENT_BINARY_DIR}/WELCOME.txt")

set(CPACK_ARCHIVE_COMPONENT_INSTALL ON)
set(CPACK_COMPONENTS_GROUPING ONE_PER_GROUP)

# coponents
set(CPACK_COMPONENTS_ALL MyApp1Devel)

# names & descriptions
set(CPACK_COMPONENT_MYAPP1DEVEL_DISPLAY_NAME "My App 1 Development")
set(CPACK_COMPONENT_MYAPP1DEVEL_DESCRIPTION "CMake support for MyApp1 package.")

# requireds

# dependencies

# groups
# Runtime

# Development
set(CPACK_COMPONENT_MYAPP1DEVEL_GROUP "Development")

