# CPack properties for my app

# components
set(CPACK_COMPONENTS_ALL ${CPACK_COMPONENTS_ALL} MyApp MyAppDevel PARENT_SCOPE)

# name & description
set(CPACK_COMPONENT_MYAPP_DISPLAY_NAME "App 1" PARENT_SCOPE)
set(CPACK_COMPONENT_MYAPPDEVEL_DISPLAY_NAME "App 1 Development" PARENT_SCOPE)

# required
set(CPACK_COMPONENT_MYAPP_REQUIRED ON PARENT_SCOPE)

# dependencies
set(CPACK_COMPONENT_MYAPPDEVEL_DEPENDS MyApp1Devel MyApp PARENT_SCOPE)

# groups
# Runtime
set(CPACK_COMPONENT_MYAPP_GROUP "Runtime" PARENT_SCOPE)

# Development
set(CPACK_COMPONENT_MYAPPDEVEL_GROUP "Development" PARENT_SCOPE)

